menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/ZeroOnet
    Rss: /atom.xml

favicon: /avatar.png
logo: /avatar.png

# Comment
# e.g disqus: seansun
disqus: zeroonet

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
